"use client";

import { useState, useEffect } from "react";
import { FiPlus, FiX, FiEdit2, FiTrash2, FiLayers, FiDollarSign, FiClock, FiSearch, FiFilter } from "react-icons/fi";
// IMPORT UTILITY KONEKSI FIRESTORE
import { db } from "../../lib/client";
import { collection, getDocs, addDoc, updateDoc, deleteDoc, doc, query, orderBy } from "firebase/firestore";

export default function ServicesCatalog() {
  // State Utama Database Layanan Jasa dari Firestore
  const [services, setServices] = useState([]);
  const [isLoading, setIsLoading] = useState(true);

  // State Kontrol UI & Form Input
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [editingService, setEditingService] = useState(null); 
  const [formData, setFormData] = useState({ name: "", category: "Perawatan Berkala", price: "", estimatedTime: "" });

  // State Filter & Search Utility System
  const [searchQuery, setSearchQuery] = useState("");
  const [categoryFilter, setCategoryFilter] = useState("all");

  // LOAD ENGINE: Ambil data master layanan jasa saat halaman dibuka
  useEffect(() => {
    fetchServicesFromFirestore();
  }, []);

  /**
   * @description Menarik data master katalog layanan jasa dari Cloud Firestore secara real-time.
   */
  const fetchServicesFromFirestore = async () => {
    try {
      setIsLoading(true);
      console.log("Firestore Catalog: Menghubungkan ke master koleksi 'services'...");
      
      const servicesRef = collection(db, "services");
      // Gunakan query opsional jika ingin mengurutkan data berdasarkan nama atau id kustom
      const snap = await getDocs(servicesRef);
      
      const masterList = snap.docs.map(docSnapshot => ({
        docId: docSnapshot.id, // Menyimpan id dokumen asli Firebase untuk mutasi
        ...docSnapshot.data()
      }));

      setServices(masterList);
      console.log("Firestore Catalog: Sinkronisasi daftar layanan sukses.");
    } catch (err) {
      console.error("Gagal memuat katalog jasa dari cloud:", err.message);
    } finally {
      setIsLoading(false);
    }
  };

  /**
   * @description Menangani proses pembuatan jasa baru atau pembaruan tarif lama (UPSERT logic).
   * Menerapkan validasi tipe data finansial sebelum melakukan commit ke database.
   * @param {Event} e - Objek event form submission
   */
  const handleSaveService = async (e) => {
    e.preventDefault();
    setIsSubmitting(true);

    try {
      if (Number(formData.price) < 0) {
        throw new Error("Tarif operasional jasa tidak diizinkan bernilai minus.");
      }

      console.log("Master Catalog Factory: Memproses sinkronisasi dokumen tarif...");

      if (editingService) {
        // --- LOGIKA MUTASI: UPDATE DATA LAMA DI FIRESTORE ---
        const docTargetRef = doc(db, "services", editingService.docId);
        await updateDoc(docTargetRef, {
          name: formData.name,
          category: formData.category,
          price: Number(formData.price),
          estimatedTime: formData.estimatedTime
        });
        console.log(`Tarif Jasa dengan ID [${editingService.id}] sukses diperbarui di cloud.`);
      } else {
        // --- LOGIKA MUTASI: CREATE DATA BARU DI FIRESTORE ---
        // Membuat kode ID kustom yang unik (Contoh: SRV-742) untuk menghindari tabrakan jika ada data dihapus
        const uniqueRandomSuffix = String(Math.floor(100 + Math.random() * 900));
        const autoGeneratedServiceId = `SRV-${uniqueRandomSuffix}`;

        await addDoc(collection(db, "services"), {
          id: autoGeneratedServiceId,
          name: formData.name,
          category: formData.category,
          price: Number(formData.price),
          estimatedTime: formData.estimatedTime,
          createdAt: new Date()
        });
        console.log("Entri item tarif jasa baru berhasil disuntikkan ke Cloud Firestore.");
      }

      // Refresh data lokal dari Firestore
      await fetchServicesFromFirestore();

      setIsModalOpen(false);
      setEditingService(null);
      setFormData({ name: "", category: "Perawatan Berkala", price: "", estimatedTime: "" });
    } catch (err) {
      alert(`Gagal menyimpan berkas katalog: ${err.message}`);
      console.error("Catalog System Error - Gagal menyimpan data jasa:", err.message);
    } finally {
      setIsSubmitting(false);
    }
  };

  /**
   * @description Mempersiapkan form modal dengan isi data lama untuk proses editing.
   * @param {Object} service - Objek data jasa yang dipilih
   */
  const startEditService = (service) => {
    setEditingService(service);
    setFormData({
      name: service.name,
      category: service.category,
      price: service.price,
      estimatedTime: service.estimatedTime
    });
    setIsModalOpen(true);
  };

  /**
   * @description Menghapus entri tarif jasa dari master katalog Cloud Firestore.
   * @param {string} docId - Unique Document ID asli Firebase
   * @param {string} serviceCustomId - ID Jasa Kustom (Contoh: SRV-001)
   */
  const handleDeleteService = async (docId, serviceCustomId) => {
    if (confirm(`Apakah Anda yakin ingin menghapus standar tarif [${serviceCustomId}] dari katalog?`)) {
      try {
        const docTargetRef = doc(db, "services", docId);
        await deleteDoc(docTargetRef);
        
        console.log(`Dokumen tarif [${serviceCustomId}] berhasil dihapus dari master katalog.`);
        await fetchServicesFromFirestore();
      } catch (err) {
        alert(`Gagal menghapus item katalog: ${err.message}`);
      }
    }
  };

  // Utility helper untuk formatting mata uang rupiah secara konsisten
  const formatRupiah = (num) => {
    return new Intl.NumberFormat("id-ID", { style: "currency", currency: "IDR", minimumFractionDigits: 0 }).format(num);
  };

  // LOGIKA KOMPUTASI FILTER & SEARCH DATA (Computed State)
  const filteredServices = services.filter(srv => {
    const serviceNameSafe = srv.name || "";
    const serviceIdSafe = srv.id || "";
    const matchesSearch = serviceNameSafe.toLowerCase().includes(searchQuery.toLowerCase()) || serviceIdSafe.toLowerCase().includes(searchQuery.toLowerCase());
    const matchesCategory = categoryFilter === "all" ? true : srv.category === categoryFilter;
    return matchesSearch && matchesCategory;
  });

  // Guarding pembagian nol jika data katalog di Firestore masih kosong murni
  const averagePriceCalculated = services.length > 0 
    ? services.reduce((acc, curr) => acc + (curr.price || 0), 0) / services.length 
    : 0;

  return (
    <div className="space-y-6 animate-fade-in text-left">
      
      {/* Page Header Area */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <h2 className="text-2xl font-bold text-white tracking-tight">Katalog Standar Jasa Servis</h2>
          <p className="text-sm text-slate-400 mt-1">Kelola standardisasi batas tarif ongkos kerja mekanik untuk menjaga transparansi dan integritas invoice konsumen.</p>
        </div>
        <button
          onClick={() => {
            setEditingService(null);
            setFormData({ name: "", category: "Perawatan Berkala", price: "", estimatedTime: "" });
            setIsModalOpen(true);
          }}
          className="bg-blue-600 hover:bg-blue-500 text-white font-semibold px-5 py-3 rounded-xl flex items-center justify-center gap-2 transition duration-200 cursor-pointer shadow-lg shadow-blue-600/10 text-sm material-ripple"
        >
          <FiPlus size={18} /> Tambah Standar Jasa
        </button>
      </div>

      {/* Main Grid Card Metrics Ringkasan */}
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
        <div className="bg-slate-900 border border-slate-800 p-5 rounded-2xl flex items-center justify-between shadow-xl">
          <div className="space-y-1">
            <p className="text-xs font-semibold text-slate-500 uppercase tracking-wider">Total Menu Layanan Jasa</p>
            <h3 className="text-2xl font-bold text-white font-mono">{isLoading ? "..." : services.length} <span className="text-xs font-normal text-slate-500 font-sans">Item Pekerjaan</span></h3>
          </div>
          <div className="w-10 h-10 bg-blue-500/10 text-blue-400 rounded-xl flex items-center justify-center border border-blue-500/20">
            <FiLayers size={20} />
          </div>
        </div>
        <div className="bg-slate-900 border border-slate-800 p-5 rounded-2xl flex items-center justify-between shadow-xl">
          <div className="space-y-1">
            <p className="text-xs font-semibold text-slate-500 uppercase tracking-wider">Rata-rata Ongkos Kerja Jasa</p>
            <h3 className="text-2xl font-bold text-emerald-400 font-mono">
              {isLoading ? "Rp ..." : formatRupiah(averagePriceCalculated)}
            </h3>
          </div>
          <div className="w-10 h-10 bg-emerald-500/10 text-emerald-400 rounded-xl flex items-center justify-center border border-emerald-500/20">
            <FiDollarSign size={20} />
          </div>
        </div>
      </div>

      {/* SEARCH BAR & FILTER TABS CONTROLS PANEL */}
      <div className="flex flex-col lg:flex-row gap-4 items-center justify-between bg-slate-900 p-4 rounded-xl border border-slate-800/80 shadow-md">
        
        {/* Search Field */}
        <div className="relative w-full lg:max-w-xs flex items-center">
          <FiSearch className="absolute left-4 text-slate-600" size={16} />
          <input
            type="text"
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            placeholder="Cari ID atau nama jasa..."
            className="w-full pl-11 pr-4 py-2.5 bg-slate-950 border border-slate-800 rounded-xl text-white placeholder:text-slate-600 focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none transition text-xs"
          />
        </div>

        {/* Category Filter Tabs */}
        <div className="flex items-center gap-1.5 w-full lg:w-auto overflow-x-auto pr-1 py-1">
          <span className="text-[10px] font-bold text-slate-500 uppercase tracking-wider hidden xl:inline flex items-center gap-1 shrink-0">
            <FiFilter size={10} /> Kategori:
          </span>
          {[
            { key: "all", label: "Semua Jasa" },
            { key: "Perawatan Berkala", label: "Berkala" },
            { key: "Keamanan & Rem", label: "Rem" },
            { key: "Sistem AC", label: "AC" },
            { key: "Perbaikan Besar", label: "Overhaul" },
            { key: "Elektrikal", label: "Elektrikal" }
          ].map(tab => (
            <button
              key={tab.key}
              onClick={() => setCategoryFilter(tab.key)}
              className={`px-3 py-1.5 rounded-lg text-xs font-medium tracking-wide transition shrink-0 cursor-pointer ${categoryFilter === tab.key ? "bg-blue-600 text-white shadow-md shadow-blue-600/10" : "bg-slate-950 text-slate-400 hover:text-slate-200 border border-slate-800/60"}`}
            >
              {tab.label}
            </button>
          ))}
        </div>

      </div>

      {/* Main Ledger Table Layout */}
      <div className="bg-slate-900 border border-slate-800 rounded-2xl overflow-hidden shadow-xl animate-fade-in">
        <div className="overflow-x-auto">
          <table className="w-full text-left border-collapse">
            <thead>
              <tr className="border-b border-slate-800 bg-slate-900/50 text-slate-400 text-xs font-semibold uppercase tracking-wider">
                <th className="px-6 py-4">ID Jasa</th>
                <th className="px-6 py-4">Nama Deskripsi Jasa Mekanik</th>
                <th className="px-6 py-4">Kategori Sektor</th>
                <th className="px-6 py-4">Estimasi Durasi Kerja</th>
                <th className="px-6 py-4">Tarif Ongkos Kerja</th>
                <th className="px-6 py-4 text-center">Tindakan Otoritas</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-800/60 text-sm text-slate-300">
              {isLoading ? (
                <tr><td colSpan={6} className="px-6 py-10 text-center text-slate-500 text-xs animate-pulse">Menghubungkan ke Pusat Data Master Katalog Jasa Bengkel...</td></tr>
              ) : filteredServices.length === 0 ? (
                <tr>
                  <td colSpan={6} className="px-6 py-10 text-center text-slate-500 text-xs">
                    Tidak ditemukan item jasa servis standar yang cocok dengan parameter pencarian.
                  </td>
                </tr>
              ) : (
                filteredServices.map((service) => (
                  <tr key={service.id || service.docId} className="hover:bg-slate-800/30 transition duration-150">
                    <td className="px-6 py-4 font-mono font-bold text-blue-400 text-xs">{service.id || "SRV-NEW"}</td>
                    <td className="px-6 py-4 font-medium text-white">{service.name}</td>
                    <td className="px-6 py-4">
                      <span className="px-2.5 py-0.5 rounded text-xs font-medium bg-slate-950 border border-slate-800/50 text-slate-400">
                        {service.category}
                      </span>
                    </td>
                    <td className="px-6 py-4 font-medium text-slate-400 inline-flex items-center gap-1.5 mt-4">
                      <FiClock size={12} className="text-slate-600" /> {service.estimatedTime}
                    </td>
                    <td className="px-6 py-4 font-mono font-bold text-emerald-400">{formatRupiah(service.price || 0)}</td>
                    <td className="px-6 py-4 text-center flex items-center justify-center gap-2">
                      <button
                        onClick={() => startEditService(service)}
                        className="p-1.5 rounded-lg bg-slate-950 text-slate-400 hover:text-blue-400 border border-slate-800 transition cursor-pointer"
                        title="Edit Item Tarif Jasa"
                      >
                        <FiEdit2 size={13} />
                      </button>
                      <button
                        onClick={() => handleDeleteService(service.docId, service.id)}
                        className="p-1.5 rounded-lg bg-slate-950 text-slate-400 hover:text-rose-400 border border-slate-800 transition cursor-pointer"
                        title="Hapus Item Jasa"
                      >
                        <FiTrash2 size={13} />
                      </button>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>

      {/* MODAL OVERLAY: FORM INPUT/EDIT MASTER TARIF JASA */}
      {isModalOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/70 backdrop-blur-sm p-4 animate-fade-in">
          <div className="bg-slate-900 border border-slate-800 rounded-3xl w-full max-w-md p-6 relative shadow-2xl">
            
            <button 
              onClick={() => {
                setIsModalOpen(false);
                setEditingService(null);
              }} 
              className="absolute right-5 top-5 p-1 rounded-lg text-slate-400 hover:text-white hover:bg-slate-800 transition cursor-pointer"
            >
              <FiX size={20} />
            </button>

            <div className="mb-6 border-b border-slate-800 pb-4">
              <span className="text-[10px] font-bold tracking-widest uppercase text-blue-500">Master Data Standardisasi</span>
              <h3 className="text-base font-bold text-white mt-0.5">
                {editingService ? "Modifikasi Tarif Jasa" : "Registrasi Standar Jasa Baru"}
              </h3>
            </div>

            <form onSubmit={handleSaveService} className="space-y-4 text-left">
              <div className="space-y-1.5">
                <label className="text-xs font-semibold text-slate-400 ml-0.5">Nama Deskripsi Jasa Perbaikan</label>
                <input
                  type="text"
                  required
                  value={formData.name}
                  onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                  placeholder="Contoh: Service Rem Set (4 Roda)"
                  className="w-full px-4 py-3 bg-slate-950 border border-slate-800 rounded-xl text-white placeholder:text-slate-600 focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none transition text-sm"
                />
              </div>

              <div className="space-y-1.5">
                <label className="text-xs font-semibold text-slate-400 ml-0.5">Sektor Kategori Kerja</label>
                <select
                  value={formData.category}
                  onChange={(e) => setFormData({ ...formData, category: e.target.value })}
                  className="w-full px-4 py-3 bg-slate-950 border border-slate-800 rounded-xl text-white focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none transition text-sm cursor-pointer"
                >
                  <option value="Perawatan Berkala">Perawatan Berkala</option>
                  <option value="Keamanan & Rem">Keamanan & Rem</option>
                  <option value="Sistem AC">Sistem AC</option>
                  <option value="Perbaikan Besar">Perbaikan Besar</option>
                  <option value="Elektrikal">Elektrikal</option>
                </select>
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-1.5">
                  <label className="text-xs font-semibold text-slate-400 ml-0.5">Estimasi Durasi Kerja</label>
                  <input
                    type="text"
                    required
                    value={formData.estimatedTime}
                    onChange={(e) => setFormData({ ...formData, estimatedTime: e.target.value })}
                    placeholder="Contoh: 45 Menit"
                    className="w-full px-4 py-3 bg-slate-950 border border-slate-800 rounded-xl text-white placeholder:text-slate-600 focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none transition text-sm"
                  />
                </div>
                <div className="space-y-1.5">
                  <label className="text-xs font-semibold text-slate-400 ml-0.5">Tarif Ongkos Kerja (IDR)</label>
                  <input
                    type="number"
                    required
                    value={formData.price}
                    onChange={(e) => setFormData({ ...formData, price: e.target.value })}
                    placeholder="Contoh: 150000"
                    className="w-full px-4 py-3 bg-slate-950 border border-slate-800 rounded-xl text-white placeholder:text-slate-600 focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none transition text-sm font-mono"
                  />
                </div>
              </div>

              <button
                type="submit"
                disabled={isSubmitting}
                className="w-full bg-blue-600 hover:bg-blue-500 text-white font-semibold py-3 rounded-xl transition duration-200 mt-6 shadow-lg shadow-blue-600/10 disabled:bg-slate-800 disabled:text-slate-500 disabled:cursor-not-allowed text-sm flex items-center justify-center"
              >
                {isSubmitting ? "Committing Document to Firestore..." : "Simpan Standar Jasa"}
              </button>
            </form>

          </div>
        </div>
      )}

    </div>
  );
}